name: Scrape preschool data

on:
  schedule:
    - cron: '0 2 * * *'  # 每天早上 10:00 (UTC+8)
  workflow_dispatch:      # 允許手動觸發

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas openpyxl

      - name: Run scraper
        run: python scrape.py

      - name: Commit and push updated data
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add data.xlsx
          git commit -m 'Update data' || echo "No changes to commit"
          git push
